import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative bg-[#f6f5f3] text-[#1a1a1a]">

        {/* GLOBAL GRID LINES */}
        <div className="pointer-events-none fixed left-12 top-0 bottom-0 w-px bg-black/10 z-0" />
        <div className="pointer-events-none fixed right-12 top-0 bottom-0 w-px bg-black/10 z-0" />

        {children}
      </body>
    </html>
  );
}
